name: Blob storage website CI

on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APPVERSION: ${{ github.run_id }}-${{ github.run_attempt }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./app
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./app
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./app
    - name: Publish
      run: dotnet publish app/app.csproj -c Release -o publishedapp
    - name: Zip Published App
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r publishedapp.zip publishedapp/**
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: publishedapp
        path: publishedapp.zip
        if-no-files-found: error
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Update VMSS 
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az vmss update -n riflelvmss -g vmss
